### ISSUE TITLE
OverflowError: Python integer -1024 out of bounds for uint16

### ISSUE THREAD

**Issue by ivishalanand** [lab-midas/TCIA_processing#3]
Getting this error
```
(tcia-processing) ➜  ThirdEyeVision python3 -W ignor
e /Users/vishalanand/Desktop/ThirdEyeVision/code/pet-ct-images/tcia_dicom_to_nifti.py /Users/vishalanand/Desktop/ThirdEyeVision/DATASET/TCIA-PETCT-DATA/manifest-1654187277763/FDG-PET-CT-Lesions /Users/vishalanand/Desktop/ThirdEyeVision/DATASET/TCIA-PETCT-DATA/manifest-1654187277763/FDG-PET-CT-Lesions-NIFTI/
  0%|                        | 0/36 [00:00<?, ?it/s]The following patient directory is being processed:  PETCT_0168f65af8
Traceback (most recent call last):
  File "/Users/vishalanand/Desktop/ThirdEyeVision/environments/tcia-processing/lib/python3.10/site-packages/dicom2nifti/convert_dir.py", line 85, in convert_directory
    convert_dicom.dicom_array_to_nifti(dicom_input, nifti_file, reorient)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/environments/tcia-processing/lib/python3.10/site-packages/dicom2nifti/convert_dicom.py", line 118, in dicom_array_to_nifti
    results = convert_generic.dicom_to_nifti(dicom_list, output_file)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/environments/tcia-processing/lib/python3.10/site-packages/dicom2nifti/convert_generic.py", line 274, in dicom_to_nifti
    data = common.get_volume_pixeldata(dicom_input)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/environments/tcia-processing/lib/python3.10/site-packages/dicom2nifti/common.py", line 312, in get_volume_pixeldata
    slice_data = _get_slice_pixeldata(slice_copy)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/environments/tcia-processing/lib/python3.10/site-packages/dicom2nifti/common.py", line 354, in _get_slice_pixeldata
    return apply_scaling(data, dicom_slice)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/environments/tcia-processing/lib/python3.10/site-packages/dicom2nifti/common.py", line 508, in apply_scaling
    return do_scaling(data, rescale_slope, rescale_intercept)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/environments/tcia-processing/lib/python3.10/site-packages/dicom2nifti/common.py", line 539, in do_scaling
    minimum_required = min([minimum_required, minimum_required * rescale_slope + rescale_intercept,
OverflowError: Python integer -1024 out of bounds for uint16
  0%|                        | 0/36 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/vishalanand/Desktop/ThirdEyeVision/code/pet-ct-images/tcia_dicom_to_nifti.py", line 215, in <module>
    convert_tcia_to_nifti(study_dirs, nii_out_root)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/code/pet-ct-images/tcia_dicom_to_nifti.py", line 199, in convert_tcia_to_nifti
    dcm2nii_CT(ct_dir, nii_out_path)
  File "/Users/vishalanand/Desktop/ThirdEyeVision/code/pet-ct-images/tcia_dicom_to_nifti.py", line 65, in dcm2nii_CT
nii = next(tmp.glob('*nii.gz'))
```

**Comment by ivishalanand** [comment]
I only downloaded a sample of data from the tcia ( 10 -12)

**Comment by crzdg** [comment]
Same for me. Which python version are you on?

**Comment by crzdg** [comment]
Using this requirements I was able to get it run on Python 3.9:

EDIT: Also tested in on Python 3.10, works as well. Python 3.11 does not work as not all requirements are available in the desired versions.


```
#
# This file is autogenerated by pip-compile with Python 3.9
# by the following command:
#
#    pip-compile --output-file=req.txt requirements.txt
#
certifi==2024.7.4
    # via requests
charset-normalizer==3.3.2
    # via requests
contourpy==1.2.1
    # via matplotlib
cycler==0.12.1
    # via matplotlib
dicom2nifti==2.3.3
    # via -r requirements.txt
fonttools==4.53.1
    # via matplotlib
h5py==3.6.0
    # via -r requirements.txt
idna==3.7
    # via requests
importlib-resources==6.4.4
    # via matplotlib
joblib==1.4.2
    # via
    #   nilearn
    #   scikit-learn
kiwisolver==1.4.5
    # via matplotlib
lxml==5.3.0
    # via nilearn
matplotlib==3.8.4
    # via -r requirements.txt
nibabel==3.2.2
    # via
    #   -r requirements.txt
    #   dicom2nifti
    #   nilearn
nilearn==0.9.1
    # via -r requirements.txt
numpy==1.22.3
    # via
    #   -r requirements.txt
    #   contourpy
    #   dicom2nifti
    #   h5py
    #   matplotlib
    #   nibabel
    #   nilearn
    #   pandas
    #   scikit-learn
    #   scipy
packaging==24.1
    # via
    #   matplotlib
    #   nibabel
pandas==2.0.3
    # via nilearn
pillow==10.4.0
    # via matplotlib
pydicom==2.3.0
    # via
    #   -r requirements.txt
    #   dicom2nifti
pyparsing==3.1.2
    # via matplotlib
python-dateutil==2.9.0.post0
    # via
    #   matplotlib
    #   pandas
pytz==2024.1
    # via pandas
requests==2.32.3
    # via nilearn
scikit-learn==1.5.1
    # via nilearn
scipy==1.11.4
    # via
    #   dicom2nifti
    #   nilearn
    #   scikit-learn
simpleitk==2.1.1.2
    # via -r requirements.txt
six==1.16.0
    # via python-dateutil
threadpoolctl==3.5.0
    # via scikit-learn
tqdm==4.64.0
    # via -r requirements.txt
tzdata==2024.1
    # via pandas
urllib3==2.2.2
    # via requests
zipp==3.20.0
    # via importlib-resources

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

**Comment by thomaskuestner** [comment]
We had initially compiled the database in Python 3.9. Thanks for pointing this out!
